[build]
  command = "npm run export"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Remove the plugin since we're doing static export
# [[plugins]]
#  package = "@netlify/plugin-nextjs"

# Primary redirect: Always send root to landing page
[[redirects]]
  from = "/"
  to = "/landing/index.html"
  status = 301
  force = true

# SPA fallbacks by section
[[redirects]]
  from = "/landing/*"
  to = "/landing/index.html"
  status = 200

[[redirects]]
  from = "/shopping-list/*"
  to = "/shopping-list/index.html"
  status = 200

# Default SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 